language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dgpg.skip=true --settings settings.xml
script: mvn deploy -DskipTests=true -Dgpg.skip=true --settings settings.xml
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: YOGZjcjYn1Lg1EC3xMalfnYTazpGWTLmIljP6l/UO92FJiLo+eUVSD5EpLFOZVCbXNAJMGWsyWoxdmr4Jjw3zT2Sj+DuLkZJMVpCe4IT+sC69z+KaWHn5fc6ax2SHYVIuZV1atxGPj6oC0tM0GHnwL+m3w6HRXb2hUboL5yiEJZhop9sk7AwjFykyDe0tBqOexZOzyya0MxviCeTnegdaqx/axrxwarLb3A/1TxYHxmAz0/CWGyc7XlEEC4uJ+jJcCM9cfBWGEqvFBZjrEDQ/4LY+DfnFD0opPovce7NDR0hjhyrgYs4bYjXZmn+E2qQmEL31b60rdZLHFthlRsk/ov7iXbsA6t2duaHAtmxhtWa05Qlx+Mo8JVHjJui0qwt8pcilc5DhU/UhZuTeksh4yAqw+RkraxgzKh5AerJO0XxC9MBNAAzro/St47U8l4x5XuSXB1fd0Q38MDvWPWZEQpA74uIpoAFPbJtakFv4tYLlCc8ltOBuEJoeeB4jF08NllmfJtMiZXbPplShOCvLvvIVkNhm4RHC2OP8Sq4D3YIwfimHMnS+G0Jvnm8TNZoCXWwp4ITeYXRtre3MD+K7BuBQ6af2gUa8aR2DYe8QsmxgYDo7HPyktcTfBY7Bo+F4v+DtEIYo7L8gwg/XJ51GWkQnJGkKYf/WaFjL6Hb8Rc=
  - secure: h5w0CYsFMX8X9n8oNId68R3U04XPd8q4x4Al2ZUj/QACos1Wcnzj+zRRGrVq4OuHVant3CQZ0WUUA6s75BFDkT7T34zY+jEt6dV7bzR/p+HcbM1WeGYUvKVq0f11Kd5Q2jhH9YlRMtOWUAejlO6O0VM1yZRLImxefdYb21zSud0C5FoXu1MkhLJXDNEGKkBjf/aBUH/MjPd08raAr36eukwClMCUvxQdms2RwG1AycAPMhBr9PJWeaTmwV6cjhz4HdlO0hqsD1Gn4M8YuEidQ48pl/jnv66gvYRQJufgwJEeH3/XNT1//XxVqGhM1hcR8a/CC1eaw7WSKRKr/fJsreAWL2ewjAHrUv/Tky5Y9sb8SrBp6hsRqoMPKpsECCYtPjxQN63QKCravCZvD9tFbTZU8mrRQmNBQ/Un+OYsh0SnkY/TKrqmWO0r38+xXMSdB4Ee+b4tnPE7YPLA9wUf3JFxIlMh4HPh7dUy5z+8Ft3gZ5g1POpXphOmlNoSWuAkAy1Ifii6NJRs+qkuoEPo9e/LW1VJXwJ/NUNbHj4jlA+m1M9HBwQfR3mtmVst+Po3y05nl1Xt7dd1iUkKO176C7p3iWOfiNVeUKMbJLuuj2pPJ7awVZT0uGPtA96Ntyf21q2qPvcPyJwYz9a7Y0M9pXg/B5oThRuL52ZiEt3CbZI=
