language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dgpg.skip=true --settings settings.xml
script: mvn deploy -DskipTests=true -Dgpg.skip=true --settings settings.xml
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: j4U47eLRk9pDkRZ+zQhy2gFknHzvjEv5sdJN4o6FUujcjozIQ/eheLy0bplgVS0zihCoPdVQNyihz19vtrm3JtvU017klhlX+IOPCFwpHjhR4omijeKDpcSH7WqcJ1WvH9Y+ZgJYBIbbC5jh5NuEdQzG8YW8200bsTU6WY5cWqcaKH5BzY54KZoHzbyywKAvA3z93E1GrGvCpg5BeM4xjWC5OeHk/1e3P5SX3NpcZ+w/cAuOTe6PbGfPatTX1ha9ZKDZ8OePDRsE1sUawSWViKhYvahx1Ne0eY046DJcKoOV4gKh71MiGECkyQrD7OJQq4p/rL3DW/p0Ls78jxkIMcX/MlpvMORvSgPHA5vkcXaX0M8Y/dnt1eUcn0ndjVmGWWNN11OnHY28HKKiDsPP8yReesMOzUKYggjEM24EMYSP8Fopl7yrRVsxkbvVXvsxU1z1Hgfv+RUEoo7hQTuDmj/g7KINW3xZX+9EoCYZFJy17rA2hytGagwrjsQcDwqfuoy3Bq7KgKtA8Xx5I0+XpyCXSl6XB1z2VcqFYIiMwfD1mDWJuhYh3ZTgyfGHgXKdPwTCdrC7vK3CHFP5eYmLmNPrMnTsbrqXuHojn/SeGlDX3shcoW7rhRDBZf9ffhtCeEZKsbDVlm7u5Na05CDmlwOycRLeCjn0gTrX70ZGlFg=
  - secure: sZ4IzK1XXwh5Z5FvNl2lvzXJoIcuJoOjoiMs7Kymr4cGGj0rggxm5vb4zr1AXS0b0n0pFZUmDlzfy3J/Xz4cBVqSIhO/Nf53+4paqqd0AC6R3LyCp1aPr1aB8pFqEvfzeYzLM7AemYTYqWP26Sp+KGXrGpdHiiKCvWSZv+vkOWDnfkCw5MClyjTJEPMaABQJsXTWIqVWhF7CP4kpgx1E22RRAsye8du7EbhR4BsZLSkeCxk1ABGjAPyKgwSqXiBwy47dg7RjdDaTt2jwsNLK8LISazM4ZW4a/E/cTg/zOBUrr6CGZi9fbye/BQ0ehEa6Wpaf4JbFy72HfadUe8RHCck/GglfjT6VhzhC/kSyJEfJKeraZHqwTypRpcQdyshmmtLOn4LI7w0WXRP8icc0r33skWq4tnuaRQwKJ76BY95VdWyeTf2AA5rUlR/DagseIqoGDbBk0iatg190ZhJN0Btk0S9tZL+PfFrfGDdaQgvtpeQC5WGOI57a9kcC9+CS9CJdkF4zdolSMGpIWvJh/gwQ2V1qpR9TPsnyvWiu+rS0m94FQOBZnTXe4n/XbnsXpdMJuOuoYQi11sxW59bYXSpJHdTD9IDwFdqpOckYvffSRPJIWg5SIQS5Rmt3NiGG4ukU2bvONYamB2//HJE4wgnn0ZR0h90NfL6WUcPPbwg=
