sudo: false
env:
  global:
  - secure: "AzM98HKS2RDP+/WdvsFiEqTbVPwLBEAtNXDQPR7cV1gAEZoNhri/iINnRAHtECgVQDt2gKmxEiyOA07zMKPpt5PwhoyZUnICwxl1t2FOkTL4LlfI+3ew1rf4F8wmaSQX/BRT7b3IgyEI0RFRCow8KH49X8xdEtAFYJB3YFu2Y6M="
  - secure: "BDNmD9y3mdZEQoFgXW2dC1FawofkThFwbITidMqeKLxSstNxQGKCpxOFAV604kaTGsf7ihpdm8WYE5IjHKTaoewdQ9hLXZPtswWXq5Ebe2gKHqJVNZa2bFD6hQBD2S7BLWWeAVIoLkyfV/QLnplOquUZTXWZ3TW2A+IXzQE+AnE="
language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
    - xorg-dev
    - libgtk-3-dev
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
# Get GCC 4.9
- wget https://github.com/Viq111/travis-container-packets/releases/download/gcc-4.9.2/gcc.tar.bz2
- tar -xjf gcc.tar.bz2
- rm gcc.tar.bz2
- export PATH=$(pwd)/gcc/bin:$PATH
- export LIBRARY_PATH=$(pwd)/gcc/lib64:$LIBRARY_PATH
- export LD_LIBRARY_PATH=$(pwd)/gcc/lib64:$LD_LIBRARY_PATH
- export CPLUS_INCLUDE_PATH=$(pwd)/gcc/include/c++/4.9.2:$CPLUS_INCLUDE_PATH
script:
- export LWJGL_BUILD_TYPE=nightly
- gradle assemble
- gradle build